### ISSUE TITLE
what about adding some upgrades to Spacebars meteor developers have been waiting for??

### ISSUE THREAD

**Issue by faceyspacey** [timbrandin/blaze-react#23]
for example to do basic math + logic in templates to achieve the canonical example of striping some table rows (based on an index):

```
<table>
 {{#each item in items}}
    <tr class="{{@index % 2 ? 'odd' : 'even'}}"></tr>
 {{/each}}
</table>
```

It seems it might be easier to achieve this here then in actual spacebars. Might be a good time/place to get these much in-demand features. Of course you first must add `@index` (which arrived in Meteor 1.2) to your to do list.

**Comment by johanbrook** [comment]
Templates shouldn't have too much logic in them. This is easily achievable with a template helper.

**Comment by timbrandin** [comment]
how about supporting both cases, if logic is added it will work, but in that case we're stepping away from Blaze. What do you prefer most?

**Comment by faceyspacey** [comment]
both cases is best of course. I assume you have lots of other stuff to do--i mainly just wanted to plant a seed. I wouldn't prioritize this. You still have other stuff not on your to do list that basically needs to be there to be fully spacebars compliant: @index as mentioned, but also things like: `{{> Template.contentBlock}}` which should translate to `this.props.children` ...And support for the elseBlock, I don't know how you wanna achieve that. You'd likely have to generate a lot more code for that sorta thing  than most the other features. 

Also does onCreated actually perfectly match up with componentDidMount, and all the other callbacks as well. 

Also in your example here you have `#each person in people` transpiling to `this.data.people.map` what if the blaze helper `people` didn't exist, and the context was passed down from a parent, would your system know to use `props` in react rather than `data` or perhaps even `state`. It seems to me there is potential for lots of ambiguous situations where React won't know where the data came from--especially since blaze has more automagic in how its lookups. It seems we could even build a lookup function of our own into react so instead of calling this.props, this.state or this.data, you call `this.lookup(key)` and it will first try props, then state, and then data. 

As far as Reactive var goes, now what about ReactiveDict, ReactiveField (@mitar's package), and ReactiveState (a nice Flux-like store package). And many other possibilities as well. How are you going to be aware of them all. 

..Not sure if you read it, but yesterday I posted a long piece in that Blaze discussion in the Meteor forum where I basically discuss shared Blaze Components interface. It looks very close to react but uses functions for things like props() instead of .props so that Tracker can make it reactive. If we can agree on this interface, you'd only have to transpile *that interface* rather than doing what you're doing now which will make it impossible for you to catch everything. Check out the piece I wrote, I think you and I can do some seriously good stuff here.

**Comment by timbrandin** [comment]
I guess we have to create some tests for both situations to make sure we create a solution that works for the transpiling of `#each person in people`.

`{{> Template.contentBlock}}` should be easy as you mentioned, do you want to start with that @faceyspacey?

About the forum post, I haven't had time to get through that, to many projects at work, and now I'm focusing on getting full Blaze 1 feature completion. Though I believe something where we make Blaze more like React is a good idea, there's a ton of good stuff combined with that!

**Comment by faceyspacey** [comment]
but that would make their code not work in Blaze anymore. i.e. if they use state and props. I think the goal should be the renderer can be switched out and their code still works.

So if were to take that route, we would need a way to describe `state` in Blaze, and ReactiveDict/Var is the only way. The parity between those and state is pretty much 1 to 1, so it makes a lot of sense. Supporting all the other packages wouldn't be necessary. We just cap it at those, and maybe ReactiveField since @mitar uses that and will likely end up invested in this project in one way or another; but ReactiveState, no. 

I'll do the `{{Template.contentBlock}}`. I think very soon we should write tests for everything we wanna support, and measure our work against that. @TwinTailsX has a separate that could be used for tests: https://github.com/TwinTailsX/sideburns-test ...It's not real tests, but just kinda manual tests to see if things are working. We should port them or use them as inspiration for the actual tests we need to write.

**Comment by mitar** [comment]
I think that Blaze now supports subexpressions. So I would not be introducing new syntax but rather support existing ones. And then you can use things like [handlebar-helpers](https://github.com/raix/Meteor-handlebar-helpers).

But I agree that templates should not have too much logic in them if we are trying to mirror current Blaze ideas. But I understand that this is contentious topic. So I think it is a good idea to support subexpressions and then people can decide to register more complicated operators inside.

Then you could do:

```
<table>
 {{#each item in items}}
    <tr class="{{$cycle @index 'odd' 'even'}}"></tr>
 {{/each}}
</table>
```

(Similar to [cycle operator in Django templates](https://docs.djangoproject.com/en/dev/ref/templates/builtins/#cycle).)

**Comment by faceyspacey** [comment]
yea, it's probably better we just support it as is. it's gonna be hard enough getting this thing to work properly in the first place. we can worry about it later at least. maybe as an optional "peer dependency" style package.

**Comment by timbrandin** [comment]
Spacebars will probably be discontinued and therefor I don't think we need to spend time on this issue.
