### ISSUE TITLE
No plugin found for template.jsx (Windows)

### ISSUE THREAD

**Issue by TwinTailsX** [timbrandin/blaze-react#25]
Hi, I'm receiving this error after adding this package to a new 1.2.1 meteor project running on Windows 7:
![](http://puu.sh/l7Wmf/ceb974a279.png)
Packages are:
```
timbrandin:sideburns
kadira:flow-router-ssr
```

I had a look at the jsx package but still not even sure where to start with debugging this... any ideas?

**Comment by TwinTailsX** [comment]
Hmm... it runs fine if I add the package locally and run it from the `packages` folder... architecture issue?

**Comment by timbrandin** [comment]
hmm, I might have to add the jsx package as an implied package for the app. I'm not sure, will need to verify this, feel free to forking and try with an imply for the jsx package. :) I have some time this weekend.

**Comment by timbrandin** [comment]
@TwinTailsX seems like you got this fixed right?

**Comment by TwinTailsX** [comment]
Indeed, appears to be fixed...
