### ISSUE TITLE
We can use SpacebarsCompiler tests

### ISSUE THREAD

**Issue by faceyspacey** [timbrandin/blaze-react#29]
https://github.com/meteor/meteor/blob/bf3bf1a7409729d38ef4c6ae7cafe37975f61c27/packages/spacebars-compiler/spacebars_tests.js

https://github.com/meteor/meteor/blob/bf3bf1a7409729d38ef4c6ae7cafe37975f61c27/packages/spacebars-compiler/compile_tests.js

we just need to change the values of `expected` to be what our transpiler will output. 

@TwinTailsX you may be interested in this aspect.

**Comment by timbrandin** [comment]
Wow, this is perfect! Will spend all weekend with this! :+1:

**Comment by faceyspacey** [comment]
the Blaze tests may be worth checking out too:

https://github.com/meteor/meteor/blob/bf3bf1a7409729d38ef4c6ae7cafe37975f61c27/packages/blaze/render_tests.js


and what might even be most pertinent right now may be @TwinTailsX 's tests repo: 
https://github.com/TwinTailsX/sideburns-test

its not real tests, but could be easily made them, or used as a smoke screen in the beginning.

**Comment by timbrandin** [comment]
Yeah, I have a similar local version of that with some more stuff, but yeah that's a good start. Though I think it's time we started adding tests to see how far we are from full Blaze 1 support.

And then we could add some graph on the projects Readme visualizing how far we are from feature complete when people can start using it, that might influence them to support us with the missing features?

Its really beneficial they have all these test already ready for us to use!

**Comment by faceyspacey** [comment]
only thing is since ur not compiling to html, but rather to jsx, ur gonna have to change the expected out to contain things like js loops and whatnot.
