### ISSUE TITLE
context + parentData tests

### ISSUE THREAD

**Issue by faceyspacey** [timbrandin/blaze-react#35]
so i tested the context feature of React and whether we could make a `parentData` feature. And guess what! We can:

http://jsfiddle.net/Ljpd0d0m
scan down to the `JamesBox` component.

I was worried that the parentData wouldnt be updated if accessed via `this.parent.props.foo` or this.parent.props.parent.props.parent.props.bar`. See what I'm saying. But that stuff is all staying up to date on its own. I.e. the parent props will be up to date. So there's no reason you can't harmlessly access them from child components. 

@aldeed 's very popular **AutoForm** package uses `Template.parentData` and likely `../../etc` spacebars expressions. For that stuff to work we have to have this feature, and we do!

...As for React's context feature--that works as planned too. Click the "INCREMENT ALL" button in the example to watch the `color` context value propagate down to any components that set it as a `contextType`. That's how we can pass the events down early on until we need dynamic css selectors + full-page selector capacity. It's also the precise way my Blaze 2.0 package will pass down helpers. So even if that doesn't end up being part of the final solution for events, it's super major for helpers. I'm planning on making my components package really popular--and if all this comes together, it will be; with react integration like so, it will be the defacto Blaze 2.0 Components package.

**Comment by aldeed** [comment]
Cool. I will look into autoform+react more after my simple-schema sprint.

**Comment by timbrandin** [comment]
wow, childContext looks great!
