### ISSUE TITLE
Cannot install the package

### ISSUE THREAD

**Issue by ansonla3** [timbrandin/blaze-react#37]
meteor add timbrandin:blaze-react
 => Errors while parsing arguments:           
                                              
While adding package timbrandin:blaze-react:
error: no such package

**Comment by faceyspacey** [comment]
it used to be called Sideburns until just this past weekend. An Atmosphere package based on the new name hasn't been made yet. Here's the old package:

https://atmospherejs.com/timbrandin/sideburns

**Comment by timbrandin** [comment]
It has been released on atmosphere now, with the name `timbrandin:blaze-react`.
