### ISSUE TITLE
Tim, check out Evan's blaze-react code

### ISSUE THREAD

**Issue by faceyspacey** [timbrandin/blaze-react#38]
https://github.com/meteor/meteor/blob/3d7632140304399642fcdba257a1e3763e6c5478/packages/blaze/blaze-react.js

I just started looking at it, so i dont know whats in there, but perhaps we can glean some ideas. I posted quite a bit in the meteor forums, and hopefully MDG's @yyx990803 comes and joins us soon. I would like to use your repo as a forum to discuss the vision I have for this whole thing. If that's not okay, let me know, given that you created the package, and I think you should get credit as the main package owner as long as possible. At this point we may have differing visions (I don't know, you haven't told me much), but you seemed to have liked a lot of what i proposed or you wouldn't have done so much of it last weekend.

**Comment by timbrandin** [comment]
I don't think that code is what they will use when they start working on Inferno, notice it dates back to may – but I might be wrong. Otherwise I'm afraid this package will be outrun by any effort done at MDG, and I'm ok with that, they have given credit in the forum for inspiring them and I'm proud to say the least of that. :)

Do you think there's any room for this package when they release Inferno?

**Comment by yyx990803** [comment]
Hey guys, thanks for chipping in on the forum. That branch was totally experimental - it was just a hack week project.

I still have some non-related work at hand to wrap up before going full speed with Inferno (not guaranteed to be the official name!), but I'm definitely keeping an eye on your effort and will most likely dig deeper when I get time :)

**Comment by timbrandin** [comment]
Cool Evan! And I do love that name! (cred to @awatson1978)

So yeah, in my opinion you can use anything in this package, for me the end
goal is not credits for anything it is to switch out Drupal with Meteor,
and this is the way towards that goal.

We haven't spent to much time documenting how this works, but basically we
first look in js files for eventmaps and load them into memory to later be
able to attach them to their corresponding template, which basically is
just a function stored in ReactTemplate global right now, and then we parse
the html files for <templates>, pass that to another step to parse all
handlebars syntax to some parts react code and some parts runtime code that
you can find in the RT global.

Lately I've been working on getting hooked onto the ecmascript compiler,
because we don't want to compete for the js extension. So right now my best
chance is by hooking into fs.writeFile (which luck is used by the babel
compiler) and load everything from the local build at start.

But if there's any chance you might get the ecmascript package to change
for possible hackability or chaining onto when files are written it would
be much easier to discover the events kept in the app and packages. And
that is our hardest task right now!

**Comment by faceyspacey** [comment]
@timbrandon I mentioned the solution for ecmascript the other day--we just do the job of ecmascript and developers don't include that package. No big deal. Sure that's a problem when packages also include ecmascript, but hardly any do yet and it will say that way since they also want their packages to work in es5. So that will stay a package that gets added on the application level. I wouldn't worry about that now. That's not the core task. By the time we are done they may have added support for multiple compilers. In the other issue I post u my code from another project for this exact thing. 

More importantly though, if u read what Geoff had to say you will see they currently have no plans to outrun your package or attempt anything of the kind. I'm not sure what u missed about what was written. They don't plan to transpirle any old blaze code. Here's the quote:

"So what we’re planning to do is to build templating on top of React, and to encourage Blaze users to upgrade to it (or, for those that prefer it, to plain React JSX). We think that this is the best possible “Blaze 2". If you choose to upgrade you’ll have to port your templates, but that’d probably be the case no matter what direction we go with Blaze 2."

They must currently think it's not possible. So there is a need for your package now more than ever.

That said @yyx990803 I'm hoping to explore other options than what was described today. If you read the issues in this forum thoroughly you will know all the strategies I've proposed to render blaze 1 via react. It doesn't need to be performant. It needs to be a stop gap for old code. MDG would be remiss to not do it if it's possible, and I may have discovered some new things since you last researched this in May.

**Comment by faceyspacey** [comment]
actually i got a bit confused with the Blaze Components version. It's actually super easy in the Blaze 1 version. It uses the instance context and props context of the current component! ...so all that's necessary is dynamically binding the event selectors, taking into consideration the whole tree. 

In Blaze Components, the state is actually the state of the parent component, which in combination with Helpers is more correct, since it lets you control state from parent components while passing down helpers and event handlers to any component that wants to use them.

**Comment by faceyspacey** [comment]
and here it is:

http://jsfiddle.net/morwkzgg

dynamic event attachment at render time. completely proven.

**Comment by timbrandin** [comment]
@faceyspacey I just came up with an idea! As events in the Template...events() are going away we can just add them after the components have mounted and updated, that way we support them, but we should promote people using inline events for future stuff they build. But we can totally get full Blaze 1 support with this strategy. And I'm about to add that tonight. :)

**Comment by timbrandin** [comment]
And also your strategy of parsing the output in the render method doesn't work, because partly JSXTransform is not supported currently and the React.renderAsStaticMarkup have been deprecated. And also doesn't that way feel a bit hackish?

**Comment by timbrandin** [comment]
Btw, should I pull out the template parts back into react-template so that you can use it for your Tracker module? Or how would you prefer us going ahead with templates for react?

**Comment by faceyspacey** [comment]
My eventual component system will promote using selectors instead. Passing down functions is retarded. The way I make this awesome is by making helpers dynamically inherited as well. From parent component to child component. So u out ur helpers and event handlers that use the same state all in the same parent component! The difference with blaze besides dynamic helper inheritance is that the state accessed by the helpers and methods is on the component where the methods are defined, not where they are implemented. Notice in blaze ur event handlers access the template instance of the child component. It's wrong.

My entire component system before blaze react solves all this beautifully. Unlike Blaze Components which did not. It should have been the way for blaze. Either way I'm bringing it to react so u don't have to engage in this god awful pattern of passing down functions and having to constantly rewrite what data u pass down. If the helpers are inherited u have less props to pass down. U saw the parent prop in my example. The reality is the whole branch re renders anyway if the parent changes--why r we doing all this work to pass down so many props when they could just be inherited in a lookup chain. The reason is cuz the pure render mixin won't play nice with this technique. So what. If u wanna make some pure components in the tree, my technique won't break it.

**Comment by faceyspacey** [comment]
Hackish. Who cares. When everyone gravitates towards its ease over the bullshit manual pass down props way, react can make a core add on out of it or something. 

As long as it works is the point. It's a stop gap. But if it works, I'll just go lower and lower level into the react code base to optimize it. Cuz like I said I want this to be component interface in general. Seperation of concerns baby! Selectors. Less props pass down boiler plate.

...If I don't have access to that stuff anymore I'll go grab the old code. The converting to HTML one isn't going anywhere. They have multiple versions of it accessible. There will always be one available. The jsx converter one may be a bit more risky, but like I said the code will exist somewhere. I'll copy it.

**Comment by faceyspacey** [comment]
I don't understand u about the template parts?

Basically no code needs to exist besides the spacebars regexes and ur build plugin.

Id get a web interface up ASAP where people can paste in spacebars code and see the output.

If u don't wanna delete ur create from blaze code etc, just make sure it doesn't break things. Envision it just as a text converter for now. That's how me and u need to interface together. And that's also a good way to look at ur project. Basically u need to keep it hyper focused on just making sure it converts properly and then me and people from the forum need to throw a bunch of code at it in the web form and get a feel for it, submit bugs. Just on the text conversion.

I got the rest my friend.
