### ISSUE TITLE
where help docs?

### ISSUE THREAD

**Issue by thearabbit** [timbrandin/blaze-react#39]
where help docs?

**Comment by timbrandin** [comment]
Sorry, we don't have any yet. And the idea is basically that it shall work as expected from Blaze 1.

**Comment by thearabbit** [comment]
Waiting you

**Comment by faceyspacey** [comment]
It's not ready yet. R u good with regexes? U can help if u want.

**Comment by timbrandin** [comment]
It's actually not far from done. I need to setup some test for the basic ones also :)
