### ISSUE TITLE
Tim, I got a plan--all we need is your base Spacebars transpilation..

### ISSUE THREAD

**Issue by faceyspacey** [timbrandin/blaze-react#40]
Check it, I just released this package:

https://github.com/ultimatejs/tracker-react

Here's an example you can get up an running with a few commands:
https://github.com/ultimatejs/tracker-react-todos-example

Basically, I'm starting to solve a lot of the dynamic behavior we talked about. BUT, the way I'm introducing it s by building it as upgrades to React for Meteor in the form of mixins. This first mixin solves the reactive helper issue (i.e. allowing reactivity beyond just `getMeteorData` ie. in actual methods). The next one will be the events one, which I posted jsfiddle research the other day for proving its possible. With those 2 things, plus your spacebars transpilation, we can put all the pieces together and make Blaze 1.0 fully renderable in Blaze. 

So, you were right, we don't need to transpile the events `.js` files. I can--and HAVE TO--do it dynamically at run/render time. 

That means all i need is a map of template names containing their rendered jsx code. No cheerio for attaching events, no tranpsiling it. And also no helper context stuff. I have to do all that super dynamically at render time. It will be easiest for me if I have a nice spacebars package (maybe called `timbrandin/spacebars-react` which you can take credit for). All you have to do when you encounter variables is: `this._lookup('foo.bar.etc')`. I'll take it from there. 

So in short, the only that must be done, is remove all the stuff I just mentioned and then complete the regexes for these 4 things:

 1. Spacebars {{#each}}
 2. Spacebars {{else}} {{/each}}
 3. Spacebars {{#with}}
 4. Spacebars {{else}} {{#with}}

And then export `SpacebarsTemplates` as a map of JSX render functions. 

You have a lot more experience with those regexes than I do, I'm sure you can do them way quicker than I can. I know you're busy as hell. I'll do this after I finish dynamic selector-based Event binding, but I figured you may wanna make your mark here. The plain spacebars transpiler will surely become widely used (and further optimized) since many similar such packages can depend on it. So I think it's important it stands alone and is included by the packages that deal with the dynamic behavior. I know I recommended close to the opposite like a week ago. But I'm not saying remove it from Sideburns--unless you want to--but strip it on its own and complete it so it can start to be used today. 

The other thing to note if it's not clear is this: we are basically making what the MDG CEO mentioned the other day. We aren't aiming for the loftier goal of rendering all of Blaze 1. Not yet. We are making the optimum Blaze 2 for React. I.e. the optimum React integration for Meteor. After this is achieved we will circle back and render blaze 1. It will be simpler then. But it's in fact easier to make the optimum React-Meteor, so we might as well make that and get that into people's hands sooner. I'm already launching the first part today. So since we can do it piece by piece (mixin by mixin, and eventually your spacebars transpiler) we can sooner get eyes on it and feedback. This will ultimately help guide MDG to make the right decisions about their final implementation--perhaps our work will become it.

**Comment by timbrandin** [comment]
Yeah, I can setup that! Should we also make blaze-react use TrackerReact ?

**Comment by faceyspacey** [comment]
Yea. I'm gonna make 4 mixins: tracker react, blaze events, subscribe react, blaze lookup. 

Then u can include em in sideburns. At this point u will have to make some minor changes to the template transpiler which I will let u know about then.

But for now let's just focus on making a second package that allows u to use spacebars with the React meteor's shipping. I'll do the mixing in part. This package will depend on a 3rd package, which is the space bar compiler.

**Comment by timbrandin** [comment]
Yeah no probs, how about you join the Slack channel in spacedropcms.org and we could chat in there?

**Comment by faceyspacey** [comment]
Ok I'm just in bed right now. I'll join u there in the future. Let's just strip it plain and add the 4 regexes. Then I'll test it and fiddle with things like exactly what js, eg lookup, we replace. Keep in mind we don't actually need that exports file which has the lookup. But we I'll have to change how the lookup method is written based on the final implementation possibly. Tho it's probably just the dot seperared string. I'm just saying don't worry about the specifics of the replace statements too much. As long as the general idea is there as a placeholder I can fiddle with it when it comes time for the final js.

So in short this package only needs the regex files and the HTML build plugin, without cheerio. U could just put all the regex in 1 file.

...I think we r gonna make a way bigger splash by releasing what we can when we have rather than waiting till we have the time to super perfect a blaze 1 renderer. So releasing tools for react instead to make it more blaze like is the perfect opportunity since we have to do it anyway. Also me personally I don't want MDG making decisions for us on how it will all come together. Their original get meteor data idea was bullshit. I just think they r gonna fuck this one up. So I wanna show me what is developers want before they get committed to the wrong path.

**Comment by timbrandin** [comment]
Alright, I'll fix that tonight. Thanks to that we're removing the events
stuff I can finally get things done here. :)

I'll add you as co-author so you can work without waiting for me, I like
the name we've got here `blaze-react`!

2015-11-23 18:18 GMT+01:00 James Gillmore <notifications@github.com>:

> Ok I'm just in bed right now. I'll join u there in the future. Let's just
> strip it plain and add the 4 regexes. Then I'll test it and fiddle with
> things like exactly what js, eg lookup, we replace. Keep in mind we don't
> actually need that exports file which has the lookup. But we I'll have to
> change how the lookup method is written based on the final implementation
> possibly. Tho it's probably just the dot seperared string. I'm just saying
> don't worry about the specifics of the replace statements too much. As long
> as the general idea is there as a placeholder I can fiddle with it when it
> comes time for the final js.
>
> So in short this package only needs the regex files and the HTML build
> plugin, without cheerio. U could just put all the regex in 1 file.
>
> ...I think we r gonna make a way bigger splash by releasing what we can
> when we have rather than waiting till we have the time to super perfect a
> blaze 1 renderer. So releasing tools for react instead to make it more
> blaze like is the perfect opportunity since we have to do it anyway. Also
> me personally I don't want MDG making decisions for us on how it will all
> come together. Their original get meteor data idea was bullshit. I just
> think they r gonna fuck this one up. So I wanna show me what is developers
> want before they get committed to the wrong path.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/timbrandin/blaze-react/issues/40#issuecomment-159000707>
> .
>



-- 
Cheers,
// Tim Brandin @timbrandin <https://twitter.com/#!/timbrandin>
http://timbrandin.com
http://studiointeract.com

**Comment by timbrandin** [comment]
It seems to be harder than just this._lookup, how about within an #each or #with we need to assign the current context for those right, do you have any suggestion on how to do that?

**Comment by faceyspacey** [comment]
The thing is I'm not so worried about exactly what js u inject, but more just the regexes and replaces with all the dollar signs I might need. Once the lookup mixin is done, I can easily pass in what I need.

Also, I forgot we also custom block helpers to transpile. The way I'd do that is generate a jsx component declaration that passes in the inner HTML as a prop rather than on props.children, perhaps passing it to ur _get method, and do the same for any else block u may enounter. See we can't use props.children because that doesn't solve else, so we might as well just pass em both in as props and find a way to turn it back into a react component. Then u transpile the actual template, which is being used as a block helper, to a render method that contains the HTML in the template and replaces Template.content/elseBlock with the 2 props passed in. I'll have to do that. So all I'll need where Template.content/elseBlock is, is: this._renderContent/Else(). Then I can access the 2 passed in props in those methods via this.props.__else/content.

**Comment by faceyspacey** [comment]
Ps check the forum, TrackerReact mixin is launched!

**Comment by timbrandin** [comment]
Have you seen my work from last night? It adds a bunch of stuff and removes the event transpiling.

**Comment by faceyspacey** [comment]
i do. it's gonna be good. we now have a solid format to nail this. over the next 2-3 weeks i'll finish the mixins, u do the remaining regexes, then u add the mixins to ur `createFromBlaze` call, we'll finalize the regexes, there will be one hiccup, we'll solve it when we get to it, and done.

**Comment by timbrandin** [comment]
Sounds like a plan, nice! :)

**Comment by faceyspacey** [comment]
...u give `TrackerReact` a test run? I just updated it so the entire render method is reactive instead, and you no longer have to specify which methods are reactive helpers as a result. It also plays nice with React's `state`-based reactivity now as well. give it a quick try--will be quite useful for you if you are using React for Meteor projects already:

```
git clone https://github.com/ultimatejs/tracker-react-todos-example.git
cd tracker-react-todos-example
meteor
```
