### ISSUE TITLE
Problem with blaze-react and sideburns

### ISSUE THREAD

**Issue by folofse** [timbrandin/blaze-react#43]
Hi

I recently updated my sideburns-version and started to get error "Cannot call method 'helpers' of undefined". I think the problem is that sideburns not parses the template nodes correctly, should I do something special to initiate sideburns / blaze-react in the newest version?

**Comment by timbrandin** [comment]
Hi @folofse, we haven't release a new version yet with all the awesome ideas from @faceyspacey. I think we will have one soon :)

**Comment by folofse** [comment]
Hi, thanks for the answer, I might be able to downgrade the sideburns-version in wait for the new version!

Looking forward to try out the new release in the future!, awesome work guys!

**Comment by laurentpayot** [comment]
I'm keeping an eye on the features list of this amazing project but this issue tells me I should wait before giving it a try. Could you guys write a couple of sentences in the README.md file just to resume its current state of usability? That would be really useful.

**Comment by timbrandin** [comment]
Yeah sure, we could do that.

2015-12-01 11:33 GMT+01:00 Laurent Payot <notifications@github.com>:

> I'm keeping an eye on the features list of this amazing project but this
> issue tells me I should wait before giving it a try. Could you guys write a
> couple of sentences in the README.md file just to resume its current state
> of usability? That would be really useful.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/timbrandin/blaze-react/issues/43#issuecomment-160928633>
> .
>



-- 
Cheers,
// Tim Brandin @timbrandin <https://twitter.com/#!/timbrandin>
http://timbrandin.com
http://studiointeract.com

**Comment by laurentpayot** [comment]
:+1:

**Comment by timbrandin** [comment]
Updated Readme.
