### ISSUE TITLE
idea: just use the Blaze compiler of Spacebars...

### ISSUE THREAD

**Issue by faceyspacey** [timbrandin/blaze-react#44]
...then take the generated code that looks like this:

```
(function(){
Template.__checkName("action_buttons");
Template["action_buttons"] = new Template("Template.action_buttons", (function() {
  var view = this;
  return HTML.DIV({
    "class": "action-button-container"
  }, "\n		", HTML.DIV({
    "class": "small-action-buttons"
  }, "\n			", Blaze.If(function() {
    return Spacebars.dataMustache(Spacebars.dot(view.lookup("currentUser"), "allowedTool"), "back");
```

and turn that into JSX. That will solve what will likely be a never-ending battle of transpiling a million spacebars edge cases.

**Comment by timbrandin** [comment]
I need to look into this!

**Comment by timbrandin** [comment]
Though there's a lot of code to achieve that transpiling which I'd like to replace with smaller regex's, here's that parsing they're doing: https://github.com/meteor/meteor/blob/dc3cd6eb92f2bdd1bb44000cdd6abd1e5d0285b1/packages/html-tools/parse.js

**Comment by faceyspacey** [comment]
Tim, if you put your transpiler up on a simple webform like this:

https://babeljs.io/repl/

we can do a lot to collaborate to finalize all the lookup behavior stuff. I'm launching all the helpers+events lookup stuff for Deep Meteor-React integration later today. 

I got a really good handle on this stuff. Take a quick run-through of this:

https://gist.github.com/faceyspacey/a6658f78e2dc80b29676

It's distilled into the simplest least amount of code possible to get the job done. That's the Blaze 2.0 behavior we wished we had. Helpers dynamically inherit similar to how event selectors work, allowing for parent components to implicitly manage state similar to React's state management model. 

I do it by transpiling the jsx (before Babel gets a hold of it) to pass down references of the parent to every child component. For example:  `<ChildComponent __parent={this} />`;

Then similar to your code I wrap `this.__lookup()` around any "helpers." In this case, the helpers can also be event handlers. So that means you don't have to waste time with the busy work of passing event handlers down either. It allows for you to designate a parent to manage state by tacking on helpers and event handlers to this parent. 

One thing different from your work is I don't lookup dot syntax: `foo.bar.baz`. I only lookup the first method after `this`, eg: 

```
this.isSelected(arg1, arg2).foo().bar()
```
 becomes:

```
this.__lookup('isSelected', [arg1, arg2]).foo().bar()
```

I'm about to integrate event handlers via selectors as method names, just to showcase another option. 

..Anyway, I'm just saying any time you're putting into all the lookup stuff we could do together if we just had an easy way for me to look at the output in a web form. The lookup stuff is rediculously easy to code if we have concrete output to look at, and can easily throw many different scenarios of spacebars at. I.e. a stable webform, rather than a sometimes broken package, etc. 

It's time to complete the spacebars. Everything else is easy from here on out.

**Comment by faceyspacey** [comment]
also real quick, just so u know where i'm coming from: im not trying to be cocky; i built an entire Blaze 2.0 framework on top of Blaze (that's part of the reason why I've been so hyped up on this operation); so I know the behavior of Blaze extremely well. if i have the correct tokens in the spacebars, i can build it overnight. i have been so busy with other stuff, but just finally got to this aspect today, and it did in a few hours. 

so thats why if it's easy for me to play with just the spacebars generation, it will be all I need to handle the other behavioral aspects. We'll use ur event strategy using addEventListeners and we could be done by the end of the week, mid-week next week at the latest.
