### ISSUE TITLE
everything besides parser prepared (Tim check this out)

### ISSUE THREAD

**Issue by faceyspacey** [timbrandin/blaze-react#45]
@timbrandin  Tim, so i made the lookups + event handlers mixins you need: 

**LOOKUP:**
https://github.com/ultimatejs/helper-lookup-blaze-react

**EVENTS:**
https://github.com/ultimatejs/event-selector-blaze-react

*note: I used a similar solution to what you did with event listeners for events.*

**REACTIVITY:**
https://github.com/ultimatejs/tracker-react

`TrackerReact` basically makes it so you don't need all the various hacks related to this:
https://github.com/timbrandin/blaze-react/blob/devel/lib/blaze-react.jsx#L59

It allows for the whole system to behave way more naturally. In, short, if you use all 3 of these mixins, all that must happens is basic recursive spacebars transpilation.

**Basically, we need to use the above code because there are the following major issues with your lookup strategy:**

 - you don't support `../..` and `Template.parentData(level)`
 - you don't support custom block helpers
 - the way you deal with helper context is happening in the wrong places. it should be purely handled from `this.__lookup()` with reactivity handled separately
 - complete dot separated prop handling
 - consequently, event handler contexts are also incorrect
 - reactivity (*Tracker.autorun*) can be offloaded to a separate mixin (i.e. *TrackerReact*)

So I added support for custom block helpers. And along the way I realized: if we made `{{#each}}` a block helper, eg: `<Each>` it would simultaneously solve block helper lookups + each looping context, and generally make parsing simpler. Basically it means you never need to generate JS constructs such as `if`, `else`, `map`, loops, etc. In handlebars, everything is either an HTML element, or a *Block Helper*. So we replicate that by making *components* for all the Handlebars block helpers. I think that is the correct approach. Check this:

```
/**
* HERE'S HOW WE TRANSPILE AN #each BLOCK:
*
* let contentBlock 	= function() { return <CONTENT_BETWEEN_#EACH_AND_ELSE_OR_/EACH />; } ;	
* let elseBlock 		= function() { return <CONTENT_BETWEEN_ELSE_AND_/EACH />; ;	
*	
* <Each parent={this} data={this.__lookup'($1', [$2])} contentBlock={contentBlock} elseBlock={elseBlock} />
**/

Each = React.createClass({
	mixins: [HandlebarsMixin],
	renderFunc() {
		let {data, parent, contentBlock, elseBlock} = this.props;
		
		if(_.isArray(data) && !_.isEmpty(data)) {
			return data.map((item, index) => {
				return this._contentBlockWithData(contentBlock, parent, item);
			});
		}
		else return elseBlock.call(parent);		//i.e. where block was defined
	}
});
```

Now imagine a custom block helper ("UnlessSpecial"). Here's what the calling code would look like in both handlebars and jsx:

---------HANDLEBARS---------
```
{{#UnlessSpecial true}}
	<div>something falsey - {{parentScopeProp}}</div>
{{else}}
	<div>someting truthy - {{parentScopeProp}}</div>
{{/unless}}
```

------------JSX-------------
```
<UnlessSpecial data={true} parent={this} 
	contentBlock={() => <div>something falsey - {this.__lookup('parentScopeProp')}</div> } 
	elseBlock={() => <div>something truthy - {this.__lookup('parentScopeProp')}</div> } 
/>
```

To see all my ***base Handlebars Components***, check this file:
https://github.com/ultimatejs/helper-lookup-blaze-react/blob/master/handlebars-components.js

...Notice how the generated JSX has no real javascript. There is very close parity between Handlebars syntax and the necessary JSX code. This will enable the most seamless transpilation. 

*Also note* how `parent={this}` is passed to all child components. It's needed to allow for `../../` and `Template.parentData()` AND to access data contexts by leaping over wrapper components such as `Each`, `With`, etc. *It's very handy to have access to a linked list of your ancestors!* It's also the one of the main differences between Handlebars and React. We can't make a complete Handlebars/Spacebars transpiler without it. **In addition, I've done tests, and it doesn't break React. Why would it? It's just a reference to a parent. If the parent is forced to update, the child is forced to update as well. Therefore the reference is always correct, and you aren't introducing side-effects into the child component. These features are at the core of my Mixins that I'm releasing to the Meteor community for React on Monday, unrelated to Blaze-React.** 

You will also notice that you don't have to do complex hard-to-track `context` passing. Because the transpiler links all components to their parent, we can always traverse the tree backwards to discover context. 

Examine the code here thoroughly. You're gonna basically see that we have *good separation of concerns* now, and likely this is the way it should be, but most importantly that no work needs to be done besides professional transpilation of spacebars.  

So that brings me to the final points. I'm not sure xregexp will cut it. 

Here's my research:

 - shitty recursive solutions and most people just recommend doing real parsing (this is a question i posted about solving the same sort of recursive problem you're trying to solve): http://stackoverflow.com/questions/34100079/need-regex-to-accomplish-basic-recursive-feature-of-language-parsers-or-help-ma?noredirect=1#comment55957633_34100079

 - handlebars react (which isn't done) is taking the full parsing approach: https://github.com/stevenvachon/handlebars-react/issues/1#issuecomment-161448218 ...here's where the core parsing code happens: https://github.com/stevenvachon/handlebars-html-parser **(one of 2 paths I recommend is we contribute to this!)**

- Blaze takes the full parsing approach. Brother, you're timing how long fancy recursive regexes take because you're thinking full parsing is too "heavy." That's how all the "big boys" are doing it. What do you think Babel is doing to parse your jsx.

- this brings me to the final point: the way MDG will eventually do this is either the way they did it in the past with their own parser OR through a Babel plugin. I've been talking to the guy who writes the guide on how to write Babel plugins! Here's our conversation: https://github.com/thejameskyle/babel-plugin-handbook/issues/20#issuecomment-162150889

I don't even think MDG will try to use their Blaze parser anymore, *if Babel has the capability to parse HTML*. It doesn't make sense to parse Spacebars separately since Babel is now handling most everything else. Babel is likely better and faster than whatever they were doing. Babel can be very efficient because transformer plugins can modify the same AST, while the parsing and code generation steps happening just once. It's very efficient and will result in less steps. There's also a simple place where we can place a "visitor" to transform the code. We just need to figure out how to write it. It will be passed the nodes of the AST perfectly. I'm studying how to build Babel plugins currently and I think you should to:

https://github.com/thejameskyle/babel-plugin-handbook

I know you exchanged a few words with MDG, but those guys aren't doing anything in this area yet. It was just an announcement in response to pressure. They're busy as hell with other things. In addition, they likely won't do it correctly. At least at the moment, they haven't exhibited the proper vision for this. As it is, they don't even believe *your project* is possible. Anyway, we can't count on them. We need to make this, and we should make it the professional way. The way that will stand the test of time. The way they will proudly incorporate into their codebase. 

...Im gonna release my mixins for React over the next few days. I didn't release them earlier in the week as I said because I wanted to make sure they matched with the similar mixins I would give you **today**. In short, we are moving the entire meteor community into the proper complete integration of Meteor + React. The only thing that will be remaining is the transpiler. 

WE NEED TO FIGURE OUT HOW TO WORK TOGETHER TO GET TRANSPILATION DONE. AND MY SENSE IS THE RECURSIVE REGEX PATH WILL NOT WORK. My sense is either a Babel plugin or contributing to https://github.com/stevenvachon/handlebars-html-parser is the path forward. 

Either way, look in my code linked above. I provide precise examples of how the outputed JSX code should look. We need to work together to achieve that. 

**OUR HOMEWORK:**

**A)** https://github.com/thejameskyle/babel-plugin-handbook

**B)** https://github.com/stevenvachon/handlebars-html-parser

***which path should we take?***

**Comment by faceyspacey** [comment]
http://stackoverflow.com/questions/1732348/regex-match-open-tags-except-xhtml-self-contained-tags/1732454#1732454

**Comment by faceyspacey** [comment]
xregexp and this: http://stackoverflow.com/questions/31989619/get-string-between-2-words-that-contain-this-words-inside-him-too/31989913#31989913 ...don't seem to capture everything. Maybe I'm missing something. Are you experiencing the same thing?

**Comment by faceyspacey** [comment]
well, after all that, i could be wrong. Check this:

https://tonicdev.com/faceyspacey/recursive-regex


...so basically you apply the recursive regex recursively on all values returned from the array until the arrays are empty. This is just the matching part, but hopefully the replaces can work as well. 

For now, im going to sleep. Im still worried that the regex way is the right way, but if we can get a quick foundation to prove this, that will save us time for the pro parser based way to some come to fruition.

**Comment by faceyspacey** [comment]
..its lookin bad. im able to recursively suck matches out correctly, but replacing them precisely back into the original string is a whole different matter.

**Comment by talha-asad** [comment]
I like the work you are doing @faceyspacey Keep it up. can't wait to use blaze-react :+1:

**Comment by faceyspacey** [comment]
@talha-asad thanks

**Comment by timbrandin** [comment]
@faceyspacey sorry, been super stressed out last month due to overload at work and partly this project, now I'm back for a while and have fixed the issues you had with recursive regex, I guess you're right on the babel plugin approach or the handlebars-html-parser, I like them both, because right now we're not notifying users of issues with their templates.

**Comment by faceyspacey** [comment]
i would say the only way is in fact basing it on Blaze and the Spacebars compiler. It comes pre-baked with all the edge cases and unique syntax scenarios of Spacebars built-in. In addition, the regex approach likely is impossible. Your recent commits seems to indicate you found solutions for a few things with the recursive regex approach, but likely it's gonna be like "wackamole" where more issues pop up just as you solve the last, and you can never get them in a state of all solved.

Either way, my friend, i pasted you the links to code that solves 100% of the core Blaze behaviors. All we need to do is pair that up with a true Spacebars compiler. I have toyed with the idea of doing it myself, but just can't find the time. Im overloaded just like you. ..The deeper I get in analyzing the future, Blaze becomes more and more obsolete. I almost don't even care any more. People just need to move their code to React themselves. That's what's going to have to happen. Doing it automatically for them may in fact be the wrong idea. It's enabling a "child" to not have to "grow up." And will likely have many many problems when they combine their blaze-to-react transpiled code with true react code. And what I foresee happening is people just giving up and rewriting things in React themselves. In short, we may serve as just n aid to see their Blaze code in React, but then after a single transpilation they have to perfect it themselves. I'm not sure I have the time to be that altruistic and give this to a bunch of Meteor developers who may not even appreciate it or even use it. Rather, I really wish I could do all this, but unfortunately I need to focus on the things that will essentially bring me in money that I desperately need right now. Fuck. 

...But when MDG makes the Spacebars transpiler for React lets revisit this.

**Comment by timbrandin** [comment]
Yeah, I've come to the same conclusion except that people really need to learn React, and new awesome things that makes the experience great will emerge! 

But just having finished this part is for me very satisfying, as I now can say it's finished enough so that it works properly.

Thx for your amazing efforts digging into this, and I to think we'd be better of for now working on projects with financial gains instead.

Yeah, let's wait and see what MDG comes up with, and people can use this project to play around with. I don't think they will learn a lot of React from it, but someone might find some use for it maybe. :)

**Comment by patrickml** [comment]
@faceyspacey & @timbrandin I just want to say great work on everything you two have done on this project. Its been nice to watch it evolve, and if it is reborn one day that would be great, but if not I hope you two were able to enjoy the progress and piece of art you two created.
